Copy InputException from jws.js
This is used in the utils.base64urldecode() function but not
defined there.

Because of this, the vep.unbundleCertsAndAssertion() function (used
in the BrowserID verifier) returns this exception message:

  ReferenceError: InputException is not defined

instead of:

  Malformed input: Illegal base64url string!